//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: i32,
    pub store_id: i32,
    pub quantity: i32,
    pub last_restocked: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::stores::Entity",
        from = "Column::StoreId",
        to = "super::stores::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Stores,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::stores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stores.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreateInventory {
    pub product_id: i32,
    pub store_id: i32,
    pub quantity: i32,
    pub last_restocked: Option<DateTimeUtc>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct UpdateInventory {
    pub product_id: Option<i32>,
    pub store_id: Option<i32>,
    pub quantity: Option<i32>,
    pub last_restocked: Option<DateTimeUtc>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct InventoryReportQueryParams {
    pub store_id: Option<i32>,
    pub product_id: Option<i32>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct InventoryReportItem {
    pub inventory_id: i32,
    pub product_id: i32,
    pub product_name: String,
    pub store_id: i32,
    pub store_name: String,
    pub quantity: i32,
    pub last_restocked: Option<DateTimeUtc>,
    pub updated_at: DateTimeUtc,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct InventoryReport {
    pub items: Vec<InventoryReportItem>,
    pub total_items: u64,
}
