//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub order_id: i32,
    pub payment_method: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub amount: Decimal,
    pub payment_date: DateTimeUtc,
    pub status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Orders,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreatePayment {
    pub order_id: i32,
    pub payment_method: String,
    pub amount: Decimal,
    pub payment_date: DateTimeUtc,
    pub status: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct UpdatePayment {
    pub order_id: Option<i32>,
    pub payment_method: Option<String>,
    pub amount: Option<Decimal>,
    pub payment_date: Option<DateTimeUtc>,
    pub status: Option<String>,
}
