//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::{entity::prelude::*, FromQueryResult};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price: Decimal,
    #[sea_orm(unique)]
    pub sku: String,
    pub category_id: i32,
    pub supplier_id: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Categories,
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::promotions::Entity")]
    Promotions,
    #[sea_orm(has_many = "super::purchase_order_items::Entity")]
    PurchaseOrderItems,
    #[sea_orm(has_many = "super::refund_items::Entity")]
    RefundItems,
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",
        to = "super::suppliers::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Suppliers,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::promotions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Promotions.def()
    }
}

impl Related<super::purchase_order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrderItems.def()
    }
}

impl Related<super::refund_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefundItems.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreateProduct {
    pub name: String,
    pub description: Option<String>,
    pub price: Decimal,
    pub sku: String,
    pub category_id: i32,
    pub supplier_id: i32,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct UpdateProduct {
    pub name: Option<String>,
    pub description: Option<String>,
    pub price: Option<Decimal>,
    pub sku: Option<String>,
    pub category_id: Option<i32>,
    pub supplier_id: Option<i32>,
}

#[derive(Debug, FromQueryResult, Serialize, Deserialize)]
pub struct ProductWithDetails {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub price: Decimal,
    pub sku: String,
    pub category_id: i32,
    pub supplier_id: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub category_name: String,
    pub supplier_name: String,
}
