//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "promotions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub promotion_type: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub value: Decimal,
    pub start_date: DateTimeUtc,
    pub end_date: DateTimeUtc,
    pub is_active: i8,
    pub product_id: Option<i32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Products,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreatePromotion {
    pub name: String,
    pub description: Option<String>,
    pub promotion_type: String,
    pub value: Decimal,
    pub start_date: DateTimeUtc,
    pub end_date: DateTimeUtc,
    pub is_active: Option<bool>,
    pub product_id: Option<i32>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct UpdatePromotion {
    pub name: Option<String>,
    pub description: Option<String>,
    pub promotion_type: Option<String>,
    pub value: Option<Decimal>,
    pub start_date: Option<DateTimeUtc>,
    pub end_date: Option<DateTimeUtc>,
    pub is_active: Option<bool>,
    pub product_id: Option<i32>,
}
